[profile.default]
solc_version = "0.8.24"
evm_version = "paris" # prevent use of PUSH0 opcode until L2 chains run out of excuses to not support it
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["lib"]

verbosity = 3

remappings = [
    "forge-std/=lib/forge-std/src/",
    "wormhole-solidity-sdk/=lib/wormhole-solidity-sdk/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "IERC20/=lib/wormhole-solidity-sdk/src/interfaces/token/",
    "SafeERC20/=lib/wormhole-solidity-sdk/src/libraries/",
    "ds-test/=lib/wormhole-solidity-sdk/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "wormhole-sdk/=lib/wormhole-solidity-sdk/src/"
]